### ISSUE TITLE
Crash (infinite loop?) for websql in Firefox/Chrome on iOS

### ISSUE THREAD

**Issue by bodaniel** [mozilla/localForage#516] opened 2016-01-29 19:39 UTC
Firefox and Chrome crashes on iOS when websql is enabled. The crash (infinite loop?) can be prevented by using only indexeddb and localstorage. The crash also happens when opening a web page in the web browser of the Facebook app on iOS.

**Comment by thgreasi** [comment] 2016-01-29 22:03
Possibly duplicate of #511

**Comment by bodaniel** [comment] 2016-02-01 13:08
https://github.com/mozilla/localForage/issues/511 seems to resolve this issue. Nice!

**Closed** 2016-02-01 17:59 UTC
