### ISSUE TITLE
Fix Web Worker support

### ISSUE THREAD

**Issue by johnmellor** [mozilla/localForage#362] opened 2015-03-23 15:44 UTC
Web Worker support was added in #144, and empirically seemed to work fine in version 0.9.1 (tested in Service Workers on Chrome), but now in version 1.2.2 it no longer works.

Commit https://github.com/mozilla/localForage/commit/69a64f8a91225ef27497e641e39d0d7ab54a3ac7 seems to be the biggest issue, but there are some other issues like uses of window.console that have been added (e.g. https://github.com/mozilla/localForage/commit/0a6bedeb81378008751d4c82c6721ad75d9e7fd1).

It would be great to restore support for Web Workers, especially since IndexedDB now works in workers in Firefox (see #350).

@dougt started hacking on this in https://github.com/dougt/push-api-appengine-demo/commit/cdb453e0aab0382a5f2a45a9152aadbf76e7e2d7, but I don't know how much remains to be done.

**Comment by tofumatt** [comment] 2015-03-23 15:46
I’ve actually been talking to @dougt about this and I’m looking at fixing it soon. :-)

**Comment by tofumatt** [comment] 2015-04-20 11:49
Duplicate of #350.

**Closed by tofumatt** 2015-04-20 11:49 UTC
