### ISSUE TITLE
localforage resolves promise on getItem non existing key

### ISSUE THREAD

**Issue by samvloeberghs** [mozilla/localForage#353] opened 2015-03-10 16:34 UTC
Hi,

I'm just wondering why the promise gets resolved when we get an item in localForage using getItem(), that does not exist? Shouldn't it reject when we call a un-existing item? Now it resolves with null

We are implementing localForage in an AngularJS project using the AngularJS directives and implementing it faces us with this issue. The promise should get rejected as the key does not exist in the local store, right?

If I'm asking a stupid question, please explain why :) It just seems logic to me to reject a key ( and value ) if it does not exists.

Thx
Sam

**Comment by thgreasi** [comment] 2015-03-10 16:44
It looks like that this is how it was designed to work.
There is a test case as well:
https://github.com/mozilla/localForage/blob/master/test/test.api.js#L258-274

**Comment by samvloeberghs** [comment] 2015-03-10 16:53
Hi @thgreasi,

I get your point. But that does not answer my question: shouldn't it reject with null and a suitable error message when trying to get an unexisting key? 

And based on your test argument, the test could also be written as

        it('returns null for undefined key [promise]', function(done) {
            localforage.getItem('key').then(function(value) {
                done();
            },
            function(err, value){
               expect(value).to.be(null);
               done();
            });
        });

Or something like that..

Right? Or am I missing something else here?
Can anybody explain me the why please? :)

Grtz

**Comment by tofumatt** [comment] 2015-03-10 17:20
The reason for this is because of how `localStorage`, the API localForage is based on, works. It returns `undefined`--not an error--for a key that doesn't exist. And when trying to create an API that uses localStorage/WebSQL/IndexedDB across all platforms, it was hard to reliably determine if a value was saved as `null` (or even `undefined`, which is a valid value to save) or if the storage API was just returning it because nothing was found.

Checking if a key exists is currently not 100% accurate with localForage. Resolving undefined keys is as-expected and as @thgreasi mentioned, we have a test case to ensure this behaviour. It might make less sense, but it's the *only* way to be consistent.

**Closed by tofumatt** 2015-03-10 17:20 UTC

**Comment by ahmedali5530** [comment] 2020-01-31 06:18
How can someone check if property exists or not localStorage supports `hasOwnProperty`, how can we do this in localForage?

**Comment by tofumatt** [comment] 2020-01-31 10:27
There's no way to check a key for being `undefined` directly, as [localForage always returns `null` for `undefined`](https://localforage.github.io/localForage/#data-api-getitem). You could [list all keys](https://localforage.github.io/localForage/#data-api-keys) and check for one if you required checking for existence rather than `null`.
