### ISSUE TITLE
Error on indexDB first startup

### ISSUE THREAD

**Issue by TCMiranda** [mozilla/localForage#492] opened 2015-12-29 20:40 UTC
Hello guys,

I'am having the same problem as this guy:
http://stackoverflow.com/questions/26843311/after-clearing-cache-and-localforage-indexeddb-getting-an-error-on-loading-the

But I found no answer.

After clearing the indexedDB storage, and starting the app normally, it fails with the following:
![captura de tela de 2015-12-29 18 32 12](https://cloud.githubusercontent.com/assets/10077439/12041664/82142af4-ae5a-11e5-993d-f350540dfc8d.png)

The line referenced is:
![captura de tela de 2015-12-29 18 33 40](https://cloud.githubusercontent.com/assets/10077439/12041682/b43f31b8-ae5a-11e5-8be9-1db8de640829.png)

My code is only opening the instance and trying to get an item:
![captura de tela de 2015-12-29 18 35 21](https://cloud.githubusercontent.com/assets/10077439/12041713/fd367f2a-ae5a-11e5-98cf-4004ee2d6095.png)
And then...
![captura de tela de 2015-12-29 18 35 38](https://cloud.githubusercontent.com/assets/10077439/12041715/01f3757c-ae5b-11e5-8828-cba0f0984809.png)

After a refresh, it runs normally.

I am using localforage 1.3.1 no promises.

Thanks!!

**Comment by TCMiranda** [comment] 2016-01-08 18:19
Anyone else experiencing this issue?

Thanks!

**Comment by sebweaver** [comment] 2016-01-10 23:40
@TCMiranda I can reproduce this error too with Chrome.

In FF, the error message is a bit different:

    InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

But the reason is the same, and I think I have figured out it.

I will commit a PR very soon to expose the problem and fix it.

**Comment by siddo420** [comment] 2016-01-20 03:40
I am getting the same error in FF. Whats the status of this issue?

```
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
var transaction = dbInfo.db.transaction(dbInfo.storeName, 'readwrite');
localforage.js (line 1608)
```

line 1608:
```
	                return value;
	            }).then(function (value) {
	                var transaction = dbInfo.db.transaction(dbInfo.storeName, 'readwrite');  //1608
	                var store = transaction.objectStore(dbInfo.storeName);
```

**Comment by tofumatt** [comment] 2016-01-20 12:28
The PR has been merged but I need to release a new version of localForage. I'll do that today and report back when it's available.

**Comment by tofumatt** [comment] 2016-01-20 12:35
Fixed and released in 7ca5b0bb64c2f07b109779622e2a018842c43aa0 and on npm. Cheers!

**Closed by tofumatt** 2016-01-20 12:35 UTC

**Comment by TCMiranda** [comment] 2016-01-20 19:30
Hi @tofumatt,

The problem at start up appears to be solved, but the rest stopped working for me, getItem and setItem not resolving.

I read some of the tests used and tried to solve my problem setting the driver and waiting for ready callback, but nothing happened.. The problem is that I am not getting any errors or warnings..

Nobody is experiencing this issue?

Thanks for your support!

**Comment by tofumatt** [comment] 2016-01-20 19:44
All the tests pass—do you mean getItem/setItem aren’t EVER resolving or just in this specific error case?

**Comment by TCMiranda** [comment] 2016-01-20 21:37
Yes, they are never resolving... Chome 48 with IndexedDB and Webpack

**Comment by sebweaver** [comment] 2016-01-21 02:29
I have created a new [PR](https://github.com/mozilla/localForage/pull/507) which should do the trick this time (with a dedicated test).

**Comment by siddo420** [comment] 2016-01-27 03:58
I think, I've hit the same problem as TCMiranda.

When are you releasing the next version (incl patch above)?

**Comment by tofumatt** [comment] 2016-01-27 17:15
I should be able to release it today, probably in a few hours :)

**Comment by TCMiranda** [comment] 2016-02-06 16:47
Only to close this subject... 1.3.3 release fixed the issue for me! 
Thanks for the support!

**Comment by gvolkan** [comment] 2016-11-03 08:53
hi, i've been used localForage for almost one year. but its happen one time and its not working until  clearing local db. 

we are using 1.4.0 version.

![image](https://cloud.githubusercontent.com/assets/10456431/19960078/44c740d0-a1b3-11e6-935e-59046688c91c.png)
