### ISSUE TITLE
It broke for browserify

### ISSUE THREAD

**Issue by bhamblok** [mozilla/localForage#412] opened 2015-08-03 10:55 UTC
Browserify does not check the existence of the "browser-field" in the npm package.json. Even with babelify, it does not work.

**Comment by thgreasi** [comment] 2015-08-03 11:14
There already exists a test case for browserify with babelify and it seems
to be working. Can you share some extra info about your configuration?

On Mon, Aug 3, 2015, 13:55 Bob Hamblok <notifications@github.com> wrote:

> Browserify does not check the existence of the "browser-field" in the npm
> package.json. Even with babelify, it does not work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/412>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by tofumatt** [comment] 2015-08-03 11:36
Looks like there's definitely a browersify issue: #413 reports it as well.

**Comment by Turbo87** [comment] 2015-08-03 11:37
I have the same issue at https://github.com/Turbo87/open-flight-planner

I worked fine with localforage v1.2.4, but breaks with v1.2.6.

**Comment by thgreasi** [comment] 2015-08-03 11:51
I will take a look at it as soon as I'm home. It's nice to have a reference
repo to work on this.

On Mon, Aug 3, 2015, 14:37 Tobias Bieniek <notifications@github.com> wrote:

> I have the same issue at https://github.com/Turbo87/open-flight-planner
>
> I worked fine with localforage v1.2.4, but breaks with v1.2.6.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/412#issuecomment-127203420>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by tofumatt** [comment] 2015-08-03 11:55
I think I know what it is. In the other example it’s someone loading src/localforage.js, not the fully built version. I never advertised this as supported but it’s worked in the past.




I’m going to push a version 1.2.7 as a fix that supports the including from `src` version, then a `1.3` that explicitly doesn’t in the changelog.




Sorry for forgetting we’d be breaking this.


- tofumatt

**Comment by tofumatt** [comment] 2015-08-03 12:08
Uploaded a new release to GitHub and npm. This should be fixed now, but there will be a new release later today: 1.3 that **will not support loading `src/localforage`** and will only work with the `dist/localforage.js` version.

**Closed by tofumatt** 2015-08-03 12:08 UTC

**Comment by Turbo87** [comment] 2015-08-03 12:12
@tofumatt I am not explicitly loading anything, I am just installing the package via npm and using browserify + babel to compile my script that imports from `localforage`. (see repo mentioned above)

**Comment by tofumatt** [comment] 2015-08-03 12:15
Yeah, we were pointing to the src/ version in the package too :-(




I’ve pushed a new version 1.2.7 that fixes it and I think I’m going to push the new es6 version as a new release entirely, because it will break compatibility with a lot of other things.




Sorry about all this. I messed up! But it should be fixed now.


- tofumatt

**Comment by Turbo87** [comment] 2015-08-03 12:44
@tofumatt no worries, thanks for the quick fix!

**Comment by thgreasi** [comment] 2015-08-03 17:23
While testing with open-flight-planner got some interesting findings:
* browserify does not like `"browser": "dist/localforage.js"`
  * it gives: `Error: Cannot find module './../utils/serializer'`
* it works fine with `"browser": "build/es5src/localforage.js",`
  * if it is included of course. The whole point of this is to leave all the project-specific babel configurations away from our users

**Comment by tofumatt** [comment] 2015-08-03 17:25
Seems like we need some better/new browserify tests.



- tofumatt

**Comment by thgreasi** [comment] 2015-08-03 17:34
It looks like that with browserify we can't just concat the files.
We 
* either need to actually use browserify to generate our build (I'm not a fan of this),
* or add the es5 sources and point browserify to them.

I like the second more (obviously just personal opinion), since my point of view while refactoring to es6 was to have minimal +-diff on the dist files.

I never actually got the old dist files to work with browserify and that is visible from our browserify test code. So I think that our build system never actually supported browserify users, or at least not without extra configuration. It seems that all this time it worked just because we were pointing them to `src/`. (On the other hand I'm not a browserify expert.)

**Comment by tofumatt** [comment] 2015-08-03 17:42
I like the idea of a minimal difference on the output, but I'd really prefer just to have one supported build file, and I'd rather not include even _more_ built files. And I really think it would be easier to support.




I think we should just use it as our built file unless it makes a huuuge difference... what does the output of the browserify version look like compared to the just es6+concat version?



- tofumatt

**Comment by thgreasi** [comment] 2015-08-03 17:53
A browserify build is generated at `test/localforage.browserify.js` after a run of `grunt test` (for the browserify tests). I'm not sure how(/if) this would work for requirejs users, but we currently include `runner.browserify.js` (an 1line file) in order to make localforage available to the global namespace.

**Comment by thgreasi** [comment] 2015-08-03 18:01
It looks like that it removes the UMD pattern.

**Comment by thgreasi** [comment] 2015-08-06 07:48
I've done some research on this during this week and this seems to be a general problem for libs that need transformations to build.
I will probably open a PR tonight that will introduce some changes to `package.json`, so that browserify users will be able to use the `src` in their build chain (like in older versions).
The PR will basically disclose our babel(ify) configuration options and transformations so that browserify-enabled apps will know how to build & require `localforage` module.

In a later PR (hopefully in a week) I will try to direct browserify users to the `dist` sources.
The are some issues there, with browserify trying to reanalyze the `require` calls of the already bundled dist file.

Such a move will probably only allow us to export the localforage namespace, encapsulating/hiding the drivers and the serializer namespaces. Any suggestion about how to expose them for plugins? Maybe something like `localforage.serializer` or `localforage.getSerializer()` ?

**Comment by tofumatt** [comment] 2015-08-06 12:50
I’m okay with `localforage.serializer`, I think even exposing that in general isn’t bad. Maybe someone wants to use the serializer directly for something and I don’t mind exposing that as an API.

- tofumatt

On 6 August 2015 at 08:48:43, Thodoris Greasidis (notifications@github.com) wrote:

I've done some research on this during this week and this seems to be a general problem for libs that need transformations to build.
I will probably open a PR tonight that will introduce some changes to package.json, so that browserify users will be able to use the src in their build chain (like in older versions).
The PR will basically disclose our babel(ify) configuration options and transformations so that browserify-enabled apps will know how to build & require localforage module.

In a later PR (hopefully in a week) I will try to direct browserify users to the dist sources.
The are some issues there, with browserify trying to reanalyze the require calls of the already bundled dist file.

Such a move will probably only allow us to export the localforage namespace, encapsulating/hiding the drivers and the serializer namespaces. Any suggestion about how to expose them for plugins? Maybe something like localforage.serializer or localforage.getSerializer() ?

**Comment by thgreasi** [comment] 2015-08-06 15:51
I would also like to suggest a localforage.getDrivet(driverName) method that will be used by setDriver internally.
Such a method would allow:
* the creation of custom drivers that extend a base driver and only override some of the methods (eg: Cordova sqlite driver(s) actually only need to override the _initStorage methods)
* the user to check whether a driver is defined

**Comment by tofumatt** [comment] 2015-08-06 15:54
That would be awesome. It would return the entire driver module, right?



- tofumatt

**Comment by thgreasi** [comment] 2015-08-06 16:47
Glad to hear it.
Yes, I guess so. It would be exactly what set Driver imports and uses.
My only extra concern, would be whether it should return a promise. With the current implementation, it should. On the other hand, since, as you said, we are dropping dynamic driver loading, it could also return a plain driver object.

**Comment by thgreasi** [comment] 2015-08-06 17:33
On the other hand, we all love promises and localforage at the moment has very few not promise-based APIs...

**Comment by tofumatt** [comment] 2015-08-06 19:01
Good point. It should return a promise that would eventually resolve to the driver, not the driver object itself :-)



- tofumatt

**Comment by af7** [comment] 2015-08-15 20:41
Hi!

1. Are the `localforage.serializer` and the rest exposed (while encapsulated) methods available for v1.3? (or will be?)

I believe that these are definitely needed because our browserify project used the `module` system, so we have no global objects. Therefore, there are problems with the `serializer`, etc. 

2. I would also like to create a custom driver and use it when all other 3 drivers are not supported. Do you expose any methods to check which driver is to be used? (like `driverSupport` but exposed)
I could use this method and if this returns `null` then I would know that all 3 drivers cannot be supported so that I then apply our custom driver (but will this work in this sequence?).

**Comment by tofumatt** [comment] 2015-08-16 03:40
Hi @af7, could you file these both as separate issues? Happy to help but we need to keep these discussions separated :smile:

If you could try installing the latest localForage from master in your project and let me know how it works with browserify that would be great. I could publish 1.3 as a beta/pre-release on npm, if that works.

**Comment by af7** [comment] 2015-08-16 08:48
Sure, I''ll transfer the 2nd bullet to a separate discussion.

1st bullet is related to this thread (browserify) and basically for when custom drivers are to be implemented. When using the `module` type (like browserify does) we do not have the `serializer` exposed, so how can we use it on our (browserify-based) project code for a custom driver that we want to develop? Unless I miss something here. So, I believe that the suggestions of @thgreasi are very valid (and actually needed in my case). I hope these methods can be exposed to the `localForage` instance (not on `global`) in the upcoming v1.3 so that we can use them now.

Thanks.

**Comment by thgreasi** [comment] 2015-08-16 11:11
Using the code from the current master, you can still require the serializer on its own. 
I will use [localForage-cordovaSQLiteDriver](https://github.com/thgreasi/localForage-cordovaSQLiteDriver/blob/master/src/localforage-cordovasqlitedriver.js#L90-L102) as an example. In that project I assume that the custom driver will be next to localforage module (like a peer dependency) and as a result the relative path (from localforage-cordovasqlitedriver.js to the serialzier.js) that is used by the `require` statement is `'./../../localforage/src/utils/serializer'`.

The "expose the serializer on the localforage namespace" is not required by the current master.
It will be a nice to have after we start using a bundler (instead of just concatenating the files), since the bundler (eg: browserify) will only expose the 'localforage' namespace.
On the other hand, if you are using browserify you will always be allowed to just require the serializer from the src folder, even after we change the source bundling mechanism. For example, `require('node_modules/localforage/src/utils/serializer')`.

**Comment by thgreasi** [comment] 2015-08-16 11:44
About point 2.
There is a [`localforage.supports()` method](https://github.com/mozilla/localForage/blob/66ed3aeb261886c60f7805a1ccdbbb59d675eae0/src/localforage.js#L338-L340) but it looks like it is not documented. It should be visible from your browser's dev tools console though.

**Comment by tofumatt** [comment] 2015-08-16 12:02
Good point, I filed #423 for that.



- tofumatt

**Comment by mshwery** [comment] 2015-08-26 14:54
I"m experiencing the same issue (https://github.com/mozilla/localForage/issues/412#issuecomment-127336708) grabbing localstorage with browserify in split bundles.

I'm on:
npm v2.14.0
browserify v11.0.1
localforage v1.2.8 (the latest available on npm)

I have a "browser" section in my package.json pointing to the actual dist file.

package.json
```json
  "browser": {
    "localforage": "./node_modules/localforage/dist/localforage.js"
  },
```

I'm grabbing all things from this "browser" property and requiring them on my vendor bundle:

gulpfile.js
```js
var browserify    = require('browserify');
var source        = require('vinyl-source-stream');
var buffer        = require('vinyl-buffer');
var vendorBundle  = browserify({ debug: false });

// grab dependencies to be bundled as a separate file `vendor.js`
var dependencies = Object.keys(require('package.json').browser).map(function(module) {
    var resolvedPath = require.resolve(module);
    vendorBundle.require(resolvedPath, { expose: module });
    return resolvedPath;
});

gulp.task('vendor-bundle', function() {
    vendorBundle.bundle()
        .pipe(source('vendor.js'))
        .pipe(buffer())
        .pipe(gulp.dest('./public/js');
});
```

I have an `app.js` that also gets browserified with babelify using:

app.js
```js
import localforage from 'localforage';
```

the build results in:
```bash
Error: Cannot find module './../utils/serializer' from './node_modules/localforage/dist'
Error: Cannot find module './drivers/indexeddb' from './node_modules/localforage/dist'
Error: Cannot find module './drivers/localstorage' from './node_modules/localforage/dist'
Error: Cannot find module './drivers/websql' from './node_modules/localforage/dist'

**Comment by mshwery** [comment] 2015-08-26 15:19
To follow up, `import` _and_ `require` output no errors if I include localforage in the main app.js bundle.

It only fails with error output when specifically grabbing the `./node_modules/localforage/dist/localforage.js` or `.min.js` variants and putting them in a separate bundle (note, this is the only package that is having any issues).

**Comment by thgreasi** [comment] 2015-08-26 16:40
@mshwery I think that you should not manually point to the dist file and [use whatever the library points in its `package.json`](https://github.com/mozilla/localForage/blob/270e84c57970c35d7a03ff8f583ddc3cb8cc9b4f/package.json#L41).

The whole point of the `browser` field, is to allow the package maintainer handle the appropriate entry point for browserify users.

>  I checked those out but their setup really isn't different than my use case...

Such an override is considered a setup difference.

**Comment by tofumatt** [comment] 2015-08-26 16:41
Agreed; we point users to a specific file as it’s the only thing we have a test case for. Other uses of localForage are unsupported, and possibly won’t work by design.


- tofumatt

**Comment by mshwery** [comment] 2015-08-26 17:20
@tofumatt @thgreasi you are probably right that I should just specify a list of modules, but in my case if the package provides `.min` versions I would rather bundle those than do minification unnecessarily myself. Whatever is in the `dist` directory should all be fully working packages without any build step (at least, for client-side packages that should be the expectation).

Regardless, I'm pointing to the exact same file as localforage's package.json: https://github.com/mozilla/localForage/blob/master/package.json#L49

**Comment by thgreasi** [comment] 2015-08-26 17:33
That's our target for v1.3 by the way.
We will drop all the module system specific fields from package.json and
point everyone to the dist file, using only the 'main' package.json field.

In any case, just trust the package.json and you will not face any problem,
even after upgrading to v1.3 (when released).

On Wed, Aug 26, 2015, 20:21 Matt Shwery <notifications@github.com> wrote:

> @tofumatt <https://github.com/tofumatt> @thgreasi
> <https://github.com/thgreasi> you are probably right that I should just
> specify a list of modules, but in my case if the package provides .min
> versions I would rather bundle those than do minification unnecessarily
> myself. Whatever is in the dist directory should all be fully working
> packages without any build step (at least, for client-side packages that
> should be the expectation).
>
> Regardless, I'm pointing to the exact same file as localforage's
> package.json:
> https://github.com/mozilla/localForage/blob/master/package.json#L49
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/412#issuecomment-135113249>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment] 2015-08-26 17:38
Also, the sources and package.json in the master branch are not the same
found in the latest release v1.2.8 (if I can remember correctly). The
master branch currently holds the sources of what will be v1.3 .

On Wed, Aug 26, 2015, 20:33 Thodoris Greasidis <thgreasi@gmail.com> wrote:

> That's our target for v1.3 by the way.
> We will drop all the module system specific fields from package.json and
> point everyone to the dist file, using only the 'main' package.json field.
>
> In any case, just trust the package.json and you will not face any
> problem, even after upgrading to v1.3 (when released).
>
> On Wed, Aug 26, 2015, 20:21 Matt Shwery <notifications@github.com> wrote:
>
>> @tofumatt <https://github.com/tofumatt> @thgreasi
>> <https://github.com/thgreasi> you are probably right that I should just
>> specify a list of modules, but in my case if the package provides .min
>> versions I would rather bundle those than do minification unnecessarily
>> myself. Whatever is in the dist directory should all be fully working
>> packages without any build step (at least, for client-side packages that
>> should be the expectation).
>>
>> Regardless, I'm pointing to the exact same file as localforage's
>> package.json:
>> https://github.com/mozilla/localForage/blob/master/package.json#L49
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mozilla/localForage/issues/412#issuecomment-135113249>
>> .
>>
> --
> *Thodoris Greasidis*
>
> Computer, Networking &
> Communications Engineer
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by tofumatt** [comment] 2015-08-26 17:55
Yup, the pre-es6-refactor branch has the code for the 1.2 branch from 1.2.7 onward (1.2.7-1.2.8).




https://github.com/mozilla/localForage/tree/pre-es6-refactor


- tofumatt

**Comment by mshwery** [comment] 2015-08-26 17:58
ah, gotcha. thanks for all the help guys!

**Comment by tofumatt** [comment] 2015-08-26 17:58
No worries, hope it helps 👍


- tofumatt
